// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class firstname_and_lastname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstname_and_lastname));
        
        string IMigrationMetadata.Id
        {
            get { return "201504290158178_firstname_and_lastname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
