// <auto-generated />
namespace DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Idontknowwhathasbeenchanged : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Idontknowwhathasbeenchanged));
        
        string IMigrationMetadata.Id
        {
            get { return "201504302124419_I don't know what has been changed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
